# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which sets up periodic OSV-Scanner scanning for vulnerabilities,
# in addition to a PR check which fails if new vulnerabilities are introduced.
#
# For more examples and options, including how to ignore specific vulnerabilities,
# see https://google.github.io/osv-scanner/github-action/

name: OSV-Scanner-Schedule-Push

on:
  schedule:
    - cron: '29 23 * * 5'
  push:
    branches: [ "main" ]

permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read
  # Read permisson for osv-scanner-reusable.
  actions: read

jobs:
  scan-schedule-push:
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@98b584ee2ed2da3935ccce10e06739d54cdcd20b" # v2.0.0
    with:
      # Example of specifying custom arguments
      scan-args: |-
        -r
        ./
